kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "build-controller.name" . }}
rules:
- apiGroups:
  - build.knative.dev
  resources:
  - builds
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - prow.k8s.io
  resources:
  - prowjobs
  verbs:
  - get
  - list
  - watch
  - update