apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "environment.controller.name" . }}
  labels:
    app: {{ template "environment.controller.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ template "environment.controller.name" . }}
    spec:
      serviceAccountName: environment-controller
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
      - name: environment-controller
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: "WEBHOOK_URL"
          value: "{{ .Values.webhookUrl }}"
        - name: "GIT_SERVER_URL"
          value: "{{ .Values.source.serverUrl }}"
        - name: "OWNER"
          value: "{{ .Values.source.owner }}"
        - name: "REPO"
          value: "{{ .Values.source.repo }}"
        # lets pretend to be in a pipeline so that we load the Pipeline User credentials
        - name: "JX_BUILD_NUMBER"
          value: "1"
        command:
{{ toYaml .Values.command | indent 10 }}
{{ if .Values.args }}
        args:
{{ toYaml .Values.args | indent 10 }}
{{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
        volumeMounts:
        - mountPath: /etc/config-logging
          name: config-logging
      volumes:
      - configMap:
          name: config-logging
        name: config-logging