apiVersion: v1
kind: Secret
metadata:
  name: environment-controller-hmac
  labels:
    app: {{ template "environment.controller.name" . }}
type: Opaque
data:  
  hmac: {{ default "" .Values.hmacToken | b64enc | quote }}
