apiVersion: v1
type: Opaque
kind: Secret
metadata:
  name: jx-pipeline-git-{{ .Values.source.gitKind }}
  annotations:
    jenkins.io/credentials-description: API Token for acccessing git for GitOps
    jenkins.io/name: Git
    jenkins.io/url: {{ .Values.source.serverUrl }}
  labels:
    jenkins.io/created-by: jx
    jenkins.io/credentials-type: usernamePassword
    jenkins.io/kind: git
    jenkins.io/service-kind: {{ .Values.source.gitKind }}
data:
  username: {{ .Values.source.user | b64enc | quote }}
  password: {{ .Values.source.token | b64enc | quote }}
