apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: environment-controller
rules:
  - apiGroups:
      - ""
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - jenkins.io
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - tekton.dev
    resources:
      - "*"
    verbs:
      - "*"
