apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "build-controller.name" . }}
  labels:
    app: {{ template "build-controller.name" . }}
spec:
  replicas: {{ .Values.buildcontroller.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ template "build-controller.name" . }}
    spec:
      serviceAccountName: {{ template "build-controller.name" . }}
      terminationGracePeriodSeconds: {{ .Values.buildcontroller.terminationGracePeriodSeconds }}
      containers:
      - name: {{ template "build-controller.name" . }}
        args:
        - --tot-url
        - http://buildnum
        - --config
        - /etc/config/config.yaml
        image: {{ .Values.buildcontroller.image.repository }}:{{ .Values.buildcontroller.image.tag }}
        imagePullPolicy: {{ .Values.buildcontroller.imagePullPolicy }}
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/started
          failureThreshold: {{ .Values.buildcontroller.failureThreshold }}
          initialDelaySeconds: {{ .Values.buildcontroller.liveInitialDelaySeconds }}
          periodSeconds: {{ .Values.buildcontroller.periodSeconds }}
          successThreshold: {{ .Values.buildcontroller.successThreshold }}
          timeoutSeconds: {{ .Values.buildcontroller.timeoutSeconds }}
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/started
          failureThreshold: {{ .Values.buildcontroller.failureThreshold }}
          initialDelaySeconds: {{ .Values.buildcontroller.readyInitialDelaySeconds }}
          periodSeconds: {{ .Values.buildcontroller.periodSeconds }}
          successThreshold: {{ .Values.buildcontroller.successThreshold }}
          timeoutSeconds: {{ .Values.buildcontroller.timeoutSeconds }}
        volumeMounts:
        - mountPath: /etc/config
          name: config
          readOnly: true
        resources:
{{ toYaml .Values.buildcontroller.resources | indent 10 }}
    {{- with .Values.buildcontroller.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.buildcontroller.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.buildcontroller.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - configMap:
          defaultMode: 420
          name: config
        name: config